export type ModeledMethodType =
  | "none"
  | "source"
  | "sink"
  | "summary"
  | "neutral";

export type Provenance =
  // Generated by the dataflow model
  | "df-generated"
  // Generated by the dataflow model and manually edited
  | "df-manual"
  // Entered by the user in the editor manually
  | "editor-manual";

export type ModeledMethod = {
  type: ModeledMethodType;
  input: string;
  output: string;
  kind: string;
  provenance: Provenance;
};

export type ModeledMethodWithSignature = {
  signature: string;
  modeledMethod: ModeledMethod;
};
