// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file remote-query-history-item-schema.proto (package docs, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { RemoteQuerySchema } from "./remote-query-schema_pb";

/**
 * @generated from message docs.RemoteQueryHistoryItemSchema
 */
export class RemoteQueryHistoryItemSchema extends Message<RemoteQueryHistoryItemSchema> {
  /**
   * @generated from field: string t = 1;
   */
  t = "";

  /**
   * @generated from field: optional string failureReason = 2;
   */
  failureReason?: string;

  /**
   * @generated from field: optional double resultCount = 3;
   */
  resultCount?: number;

  /**
   * @generated from field: string status = 4;
   */
  status = "";

  /**
   * @generated from field: bool completed = 5;
   */
  completed = false;

  /**
   * @generated from field: string queryId = 6;
   */
  queryId = "";

  /**
   * @generated from field: docs.RemoteQuerySchema remoteQuery = 7;
   */
  remoteQuery?: RemoteQuerySchema;

  /**
   * @generated from field: optional string userSpecifiedLabel = 8;
   */
  userSpecifiedLabel?: string;

  constructor(data?: PartialMessage<RemoteQueryHistoryItemSchema>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "docs.RemoteQueryHistoryItemSchema";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "t", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    {
      no: 2,
      name: "failureReason",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
    {
      no: 3,
      name: "resultCount",
      kind: "scalar",
      T: 1 /* ScalarType.DOUBLE */,
      opt: true,
    },
    { no: 4, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "completed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "queryId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "remoteQuery", kind: "message", T: RemoteQuerySchema },
    {
      no: 8,
      name: "userSpecifiedLabel",
      kind: "scalar",
      T: 9 /* ScalarType.STRING */,
      opt: true,
    },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): RemoteQueryHistoryItemSchema {
    return new RemoteQueryHistoryItemSchema().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): RemoteQueryHistoryItemSchema {
    return new RemoteQueryHistoryItemSchema().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): RemoteQueryHistoryItemSchema {
    return new RemoteQueryHistoryItemSchema().fromJsonString(
      jsonString,
      options,
    );
  }

  static equals(
    a:
      | RemoteQueryHistoryItemSchema
      | PlainMessage<RemoteQueryHistoryItemSchema>
      | undefined,
    b:
      | RemoteQueryHistoryItemSchema
      | PlainMessage<RemoteQueryHistoryItemSchema>
      | undefined,
  ): boolean {
    return proto3.util.equals(RemoteQueryHistoryItemSchema, a, b);
  }
}
