// @generated by protoc-gen-es v1.0.0 with parameter "target=ts"
// @generated from file variant-analysis-skipped-repo-schema.proto (package docs, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message docs.VariantAnalysisSkippedRepoSchema
 */
export class VariantAnalysisSkippedRepoSchema extends Message<VariantAnalysisSkippedRepoSchema> {
  /**
   * @generated from field: optional int64 id = 1;
   */
  id?: bigint;

  /**
   * @generated from field: string fullName = 2;
   */
  fullName = "";

  /**
   * @generated from field: optional bool private = 3;
   */
  private?: boolean;

  /**
   * @generated from field: optional double stargazersCount = 4;
   */
  stargazersCount?: number;

  /**
   * @generated from field: optional string updatedAt = 5;
   */
  updatedAt?: string;

  constructor(data?: PartialMessage<VariantAnalysisSkippedRepoSchema>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "docs.VariantAnalysisSkippedRepoSchema";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 2, name: "fullName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "private", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 4, name: "stargazersCount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 5, name: "updatedAt", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VariantAnalysisSkippedRepoSchema {
    return new VariantAnalysisSkippedRepoSchema().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VariantAnalysisSkippedRepoSchema {
    return new VariantAnalysisSkippedRepoSchema().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VariantAnalysisSkippedRepoSchema {
    return new VariantAnalysisSkippedRepoSchema().fromJsonString(jsonString, options);
  }

  static equals(a: VariantAnalysisSkippedRepoSchema | PlainMessage<VariantAnalysisSkippedRepoSchema> | undefined, b: VariantAnalysisSkippedRepoSchema | PlainMessage<VariantAnalysisSkippedRepoSchema> | undefined): boolean {
    return proto3.util.equals(VariantAnalysisSkippedRepoSchema, a, b);
  }
}

